services:
  phase3:
    build:
      context: .
      dockerfile: Dockerfile.full
    container_name: magnetic_phase3
    working_dir: /app
    environment:
      - WORKFLOW=full
      - DISPLAY=:0
      - LIBGL_ALWAYS_INDIRECT=1
      - SOFT_MESH_CSV=/app/phase3_results/csv/soft_mesh.csv
      - HARD_MESH_CSV=/app/phase3_results/csv/hard_mesh.csv
    volumes:
      # Phase3 results
      - ./phase3_results/csv:/app/phase3_results/csv
      - ./phase3_results/plots:/app/phase3_results/plots
      - ./phase3_results/reports:/app/phase3_results/reports
      - ./phase3_results/logs:/app/phase3_results/logs
      # Common inputs / FEA data
      - ./common_inputs/csv:/app/common_inputs/csv
    tty: true
    stdin_open: true
